  PayMerchantService:
    Db:
      LogsConnString:
        settings-key: LykkePayLogsConnString
        types: [AzureTableStorage, Tag]
      MerchantConnString:
        settings-key: LykkePayMerchantDataConnString
        types: [AzureTableStorage, Tag]
  MonitoringServiceClient:
    MonitoringServiceUrl:
      settings-key: MonitoringServiceUrl
      types: [Tag]
  SlackNotifications:
    AzureQueue:
      ConnectionString:
        settings-key: SlackNotificationsConnString
        types: [AzureTableStorage]
      QueueName: slack-notifications